import type { Metadata } from "next";
import "./globals.css";

import { comfortaa } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import FooterComponent from "../components/FooterComponent";
import Navbar from "../components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} antialiased bg-[#171717] text-[#ededed]`}
      >
        <Navbar />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
